version: '3'

services:
  couchbasedb:
    build: ./docker/couchbase
    container_name: bitdistrict-couchbase
    networks:
      - bitdistrict-network
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=travel-sample
      - COUCHBASE_BUCKET_PASSWORD=
    ports:
     - 8091:8091
     - 8092:8092
     - 8093:8093
     - 8094:8094
  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: bitdistrict-nodejs
    command: /docker-setup.sh
    environment:
      - NODE_ENV=development
      - DOCKER=true
      - COPE_DB_HOST
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - couchbasedb
    depends_on:
      - couchbasedb
    networks:
      - bitdistrict-network
    ports:
      - 3000:3000
      - 56745:56745 #debug port
networks:
  bitdistrict-network:
